import "./global.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Providers from "./components/lib/providers";
import Footer from "./components/Footer";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-[#FCFCFC] dark:bg-black ${inter.className}`}>
        <Providers>
          <Header />
          <div className="pt-32">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
